//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotKeySystem_example.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class HotKeySettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static HotKeySettings defaultInstance = ((HotKeySettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new HotKeySettings())));
        
        public static HotKeySettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F1")]
        public string ShowHelpCommandKeyHotKey {
            get {
                return ((string)(this["ShowHelpCommandKeyHotKey"]));
            }
            set {
                this["ShowHelpCommandKeyHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control+B")]
        public string FancyBegruessungCommandKeyHotKey {
            get {
                return ((string)(this["FancyBegruessungCommandKeyHotKey"]));
            }
            set {
                this["FancyBegruessungCommandKeyHotKey"] = value;
            }
        }
    }
}
