//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gabo.MapEditor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class HotKeySettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static HotKeySettings defaultInstance = ((HotKeySettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new HotKeySettings())));
        
        public static HotKeySettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F5")]
        public string RefreshCommandKeyHotKey {
            get {
                return ((string)(this["RefreshCommandKeyHotKey"]));
            }
            set {
                this["RefreshCommandKeyHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F1")]
        public string ShowHelpCommandKeyHotKey {
            get {
                return ((string)(this["ShowHelpCommandKeyHotKey"]));
            }
            set {
                this["ShowHelpCommandKeyHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F2")]
        public string ShowAboutCommandKeyHotKey {
            get {
                return ((string)(this["ShowAboutCommandKeyHotKey"]));
            }
            set {
                this["ShowAboutCommandKeyHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control+E")]
        public string ExportProjectCommandKeyHotKey {
            get {
                return ((string)(this["ExportProjectCommandKeyHotKey"]));
            }
            set {
                this["ExportProjectCommandKeyHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control+M")]
        public string ImportProjectCommandKeyHotKey {
            get {
                return ((string)(this["ImportProjectCommandKeyHotKey"]));
            }
            set {
                this["ImportProjectCommandKeyHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control+S")]
        public string SaveProjectCommandKeyHotKey {
            get {
                return ((string)(this["SaveProjectCommandKeyHotKey"]));
            }
            set {
                this["SaveProjectCommandKeyHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control+K")]
        public string ShowCopyProjectCommandKeyHotKey {
            get {
                return ((string)(this["ShowCopyProjectCommandKeyHotKey"]));
            }
            set {
                this["ShowCopyProjectCommandKeyHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control+N")]
        public string ShowNewProjectCommandKeyHotKey {
            get {
                return ((string)(this["ShowNewProjectCommandKeyHotKey"]));
            }
            set {
                this["ShowNewProjectCommandKeyHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control+O")]
        public string ShowProjectExplorerCommandKeyHotKey {
            get {
                return ((string)(this["ShowProjectExplorerCommandKeyHotKey"]));
            }
            set {
                this["ShowProjectExplorerCommandKeyHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control+G")]
        public string ShowProjectPropertiesCommandKeyHotKey {
            get {
                return ((string)(this["ShowProjectPropertiesCommandKeyHotKey"]));
            }
            set {
                this["ShowProjectPropertiesCommandKeyHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control+P")]
        public string ShowPublishProjectCommandKeyHotKey {
            get {
                return ((string)(this["ShowPublishProjectCommandKeyHotKey"]));
            }
            set {
                this["ShowPublishProjectCommandKeyHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control+I")]
        public string ShowImportCommandKeyHotKey {
            get {
                return ((string)(this["ShowImportCommandKeyHotKey"]));
            }
            set {
                this["ShowImportCommandKeyHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control+L")]
        public string CloseProjectCommandKeyHotKey {
            get {
                return ((string)(this["CloseProjectCommandKeyHotKey"]));
            }
            set {
                this["CloseProjectCommandKeyHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control+A")]
        public string SelectAllCommandKeyHotKey {
            get {
                return ((string)(this["SelectAllCommandKeyHotKey"]));
            }
            set {
                this["SelectAllCommandKeyHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Delete")]
        public string DeleteSelectionCommandKeyHotKey {
            get {
                return ((string)(this["DeleteSelectionCommandKeyHotKey"]));
            }
            set {
                this["DeleteSelectionCommandKeyHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control+C")]
        public string CopySelectedPositionsCommandKeyHotKey {
            get {
                return ((string)(this["CopySelectedPositionsCommandKeyHotKey"]));
            }
            set {
                this["CopySelectedPositionsCommandKeyHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control+V")]
        public string AddCopiedPositionsCommandKeyHotKey {
            get {
                return ((string)(this["AddCopiedPositionsCommandKeyHotKey"]));
            }
            set {
                this["AddCopiedPositionsCommandKeyHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control+D")]
        public string TogglePositionsOrientationVisibilityCommandKeyHotKey {
            get {
                return ((string)(this["TogglePositionsOrientationVisibilityCommandKeyHotKey"]));
            }
            set {
                this["TogglePositionsOrientationVisibilityCommandKeyHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Escape")]
        public string ResetMapToolsCommandKeyHotKey {
            get {
                return ((string)(this["ResetMapToolsCommandKeyHotKey"]));
            }
            set {
                this["ResetMapToolsCommandKeyHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RightClick")]
        public string ResetMapToolsCommandMouseHotKey {
            get {
                return ((string)(this["ResetMapToolsCommandMouseHotKey"]));
            }
            set {
                this["ResetMapToolsCommandMouseHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+RightClick")]
        public string ResetLineCreatorCommandMouseHotKey {
            get {
                return ((string)(this["ResetLineCreatorCommandMouseHotKey"]));
            }
            set {
                this["ResetLineCreatorCommandMouseHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control+WheelClick")]
        public string MagnifierZoomCommandMouseHotKey {
            get {
                return ((string)(this["MagnifierZoomCommandMouseHotKey"]));
            }
            set {
                this["MagnifierZoomCommandMouseHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control+LeftClick")]
        public string StartMapSelectionBoxCommandMouseHotKey {
            get {
                return ((string)(this["StartMapSelectionBoxCommandMouseHotKey"]));
            }
            set {
                this["StartMapSelectionBoxCommandMouseHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LeftShift")]
        public string ShowLineConnectionPointsCommandKeyHotKey {
            get {
                return ((string)(this["ShowLineConnectionPointsCommandKeyHotKey"]));
            }
            set {
                this["ShowLineConnectionPointsCommandKeyHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+WheelClick")]
        public string RotatePositionCreatorCommandMouseHotKey {
            get {
                return ((string)(this["RotatePositionCreatorCommandMouseHotKey"]));
            }
            set {
                this["RotatePositionCreatorCommandMouseHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control+R")]
        public string ShowRouteResultCommandKeyHotKey {
            get {
                return ((string)(this["ShowRouteResultCommandKeyHotKey"]));
            }
            set {
                this["ShowRouteResultCommandKeyHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control+RightClick")]
        public string ResetMagnifierCommandMouseHotKey {
            get {
                return ((string)(this["ResetMagnifierCommandMouseHotKey"]));
            }
            set {
                this["ResetMagnifierCommandMouseHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+RightClick")]
        public string ResetPositionCreatorCommandMouseHotKey {
            get {
                return ((string)(this["ResetPositionCreatorCommandMouseHotKey"]));
            }
            set {
                this["ResetPositionCreatorCommandMouseHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+RightClick")]
        public string ResetCreatorsCommandMouseHotKey {
            get {
                return ((string)(this["ResetCreatorsCommandMouseHotKey"]));
            }
            set {
                this["ResetCreatorsCommandMouseHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control+Z")]
        public string UndoCommandKeyHotKey {
            get {
                return ((string)(this["UndoCommandKeyHotKey"]));
            }
            set {
                this["UndoCommandKeyHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control+T")]
        public string UnlockProjectCommandKeyHotKey {
            get {
                return ((string)(this["UnlockProjectCommandKeyHotKey"]));
            }
            set {
                this["UnlockProjectCommandKeyHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control+W")]
        public string DiscardChangesCommandKeyHotKey {
            get {
                return ((string)(this["DiscardChangesCommandKeyHotKey"]));
            }
            set {
                this["DiscardChangesCommandKeyHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Alt+F4")]
        public string ExitCommandKeyHotKey {
            get {
                return ((string)(this["ExitCommandKeyHotKey"]));
            }
            set {
                this["ExitCommandKeyHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shift+LeftClick")]
        public string MultiSelectMapObjectsCommandMouseHotKey {
            get {
                return ((string)(this["MultiSelectMapObjectsCommandMouseHotKey"]));
            }
            set {
                this["MultiSelectMapObjectsCommandMouseHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control+Plus")]
        public string ShowNewLayerCommandKeyHotKey {
            get {
                return ((string)(this["ShowNewLayerCommandKeyHotKey"]));
            }
            set {
                this["ShowNewLayerCommandKeyHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control+Minus")]
        public string DeleteLayerCommandKeyHotKey {
            get {
                return ((string)(this["DeleteLayerCommandKeyHotKey"]));
            }
            set {
                this["DeleteLayerCommandKeyHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Alt+Up")]
        public string IncreaseLayerOrderCommandKeyHotKey {
            get {
                return ((string)(this["IncreaseLayerOrderCommandKeyHotKey"]));
            }
            set {
                this["IncreaseLayerOrderCommandKeyHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Alt+Down")]
        public string DecreaseLayerOrderCommandKeyHotKey {
            get {
                return ((string)(this["DecreaseLayerOrderCommandKeyHotKey"]));
            }
            set {
                this["DecreaseLayerOrderCommandKeyHotKey"] = value;
            }
        }
    }
}
